[package]
name = "todo-tui"
version = "0.5.1"
edition = "2021"
description = "A terminal todo app for niri"

[[bin]]
name = "todo-tui"
path = "src/bin/todo-tui.rs"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
arboard = { version = "3", default-features = false }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
incremental = false
opt-level = "z"
strip = true
rpath = false
debug = false
debug-assertions = false
overflow-checks = false
